### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by tedmiston** [teamclairvoyant/airflow-maintenance-dags#5]
Hey @rssanders3 - I'm running a large number of Airflow instances in a cluster environment and would love to get more info around how you're using these scripts.

For db-cleanup, do you really delete rows out of task_instance, dag_run, etc in a prod database?  I've always thought of that as a source of truth to keep forever.  That aside, my Airflow DBs are growing.  For example, ~5M rows in task_instance.  I haven't really taken the time to profile Airflow's queries to determine if/when this becomes significant.

For log-cleanup, are you running something similar on scheduler logs or the logs from the DAG file processor?  I've definitely seen those get big.  I've been wondering about the best way to deal with this inside/outside Airflow.  Wondering if configuring log rotation is the best solution.

Happy to chat over email / gitter / slack / etc if there's a better channel for discussion.

**Comment by rssanders3** [comment]
Hello @tedmiston, I'm sorry for not getting back to you sooner.

We use these DAGs optionally depending on the situation and use case. 

Regarding the **db-cleanup** DAG, I would agree with you that ideally you'd like a full history of the dag runs, task instances, log entries, etc. However depending on the amount of space you have on your DB, the length of time you intended to have the Airflow Instance/Cluster running and the number of jobs you have running, you may come across a time in which the DB is completely filled with data from several years ago that you might not find relevant. We haven't quite gotten to this stage yet as we've been able to create DBs with plenty of space, but sometimes the metastore DB is used for other things that require quite a bit of space. Thus, we want to ensure that Airflow doesn't take too much space and only retain the most recent data.

The **log-cleanup** DAG was built to get rid of the task instance logs. Like the DB, we're working with a limited amount of space and thus tried to create a dag that can clear away less relevant logs to ensure our machines don't get filled up. The DAG is currently not setup to delete Scheduler, Worker, or Web Server logs. The reason for this is because we usually setup SystemD to control the Daemons. This in turn allows the logs to be managed by journalctl which handles archiving and deleting old logs. How do you currently populate your Scheduler, Worker, or Web Server logs?

If you would like we can certainly discuss this more over any means you'd like and discuss your use case in more detail to see if they meet your usec ase and/if they can be extended.
