### ISSUE TITLE
How to guarantee that the maintenance will run on every worker.

### ISSUE THREAD

**Issue by akhilbatra898** [teamclairvoyant/airflow-maintenance-dags#62]
https://github.com/teamclairvoyant/airflow-maintenance-dags/blob/2512cd500da4056086c57bcce9e96a4fe5ec6f86/log-cleanup/airflow-log-cleanup.py#L114

^ How does running multiple instances of task with a different id guarantee that the maintenance ran on every worker node?

**Comment by rssanders3** [comment]
There, unfortunately, isn't a way to guarantee a task will be executed on a specific worker instance (short of forcing a task to SSH onto that particular machine and execute the cleanup process which is difficult because you need to setup passwordless SSH). Setting the NUMBER_OF_WORKERS value is merely to increase the probability of it running across multiple workers. On one day there is a possibility that the process won't run on a worker, but it should eventually run on the missed instance by probability in one of the subsequent runs.
