### ISSUE TITLE
Guaranteed cleanup in all workers?

### ISSUE THREAD

**Issue by akhilbatra898** [teamclairvoyant/airflow-maintenance-dags#71]
https://github.com/teamclairvoyant/airflow-maintenance-dags/blob/29b358afffd90f7a5c583f0ff2b9902bf917a4dc/log-cleanup/airflow-log-cleanup.py#L169

^Does this guarantee cleanup in all workers. 

Consider scenario where one worker can have more than one slot in the pool config.

**Comment by rssanders3** [comment]
This sadly doesn't guarantee that the logs will be cleaned up on all the workers. It merely increases the odds of the cleanup being run on all the workers. This is sadly the best we can do since if you have multiple workers running to handle tasks, there's no way to force a task to be run on a particular machine. 
If you have this running regularly though, it should eventually clear out all the workers at some point. One worker might be behind for a couple of days but this shouldn't cause any major issue.

**Comment by akhilbatra898** [comment]
oh cool thanks :)
